### PR TITLE
Release lock after saving complete when Bukkit.unloadWorld is called

### PR DESCRIPTION
**Pull request by emmanuelvlad**
This is my solution for the issue #55 

I didn't test the default loaders, but it should be fine since I just call `unlockWorld()` if `releaseLock` is true

### CODE REVIEW

**Comment by ComputerNerd100** [comment]
This looks pretty good to me overall at first glance
@Paul19988 @Owen1212055 Thoughts from you both would be great
@emmanuelvlad Can you confirm what has/hasn't been tested on your end?
Thanks!

**Comment by emmanuelvlad** [comment]
> @emmanuelvlad Can you confirm what has/hasn't been tested on your end? Thanks!

Sure, I've tested it with the default `FileLoader` and a custom Loader I made for my own service (grpc)

I didn't test the following loaders: `RedisLoader`, `MongoLoader` and `MysqlLoader`

**Comment by emmanuelvlad** [comment]
bump

**Comment by kyngs** [comment]
I have a small issue with this. In the current state it breaks API compatibility for all custom slimeloader implementations.

**Comment by kyngs** [comment]
The locking system was retired, I think this should probably be closed.

**Pull request closed without merging**
